version: "3.9"
services:
  manager:
    hostname: manager
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - test-network
    env_file: .env.manager
    restart: unless-stopped
  worker-1:
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - test-network
    ports:
      - "80:80"
    env_file: .env.worker
    restart: unless-stopped
  worker-2:
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - test-network
    ports:
      - "81:80"
    env_file: .env.worker
    restart: unless-stopped

networks:
  test-network:
    name: test-network
  